# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=100)),
                ('photo_caption', models.CharField(max_length=100)),
                ('photo_file', models.FileField(upload_to=b'')),
                ('photo_filetype', models.CharField(default='unknown', max_length=10)),
                ('photo_uploadtime', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(default='publicuser', max_length=30)),
            ],
            options={
                'db_table': 'photo',
                'indexes': [],
            },
        ),
    ]
