# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-20 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_filetype',
        ),
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
