# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20160920_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_caption',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
